### ISSUE TITLE
problem running cmb 2.2.45 with datastax enterprise 4.7.0

### ISSUE THREAD

**Issue by yeiniel** [Comcast/cmb#45]
Hello everyone

I where trying to run cmb 2.2.45 on top of datastax enterprise 4.7.0 and this error messages came out every time y run the cmb.sh command line script:

2015-06-30 10:12:20,587 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  ConnectionPoolMBeanManager - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=CMBAstyananxConnectionPool,ServiceType=connectionpool
2015-06-30 10:12:20,605 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - AddHost: 192.168.1.217
2015-06-30 10:12:20,667 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - RemoveHost: 192.168.1.217
2015-06-30 10:12:20,763 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - AddHost: 192.168.1.217
2015-06-30 10:12:20,765 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - RemoveHost: 192.168.1.217
2015-06-30 10:12:20,768 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - AddHost: 192.168.1.217
2015-06-30 10:12:20,778 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CountingConnectionPoolMonitor - RemoveHost: 192.168.1.217
2015-06-30 10:12:20,780 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] INFO  CQSControllerServlet - event=ping version=2.2.45 ip=127.0.1.1 port=6059
2015-06-30 10:12:21,019 [main] [b27b0f1e-1df1-472d-a81e-305862b698d9] WARN  CQSControllerServlet - event=ping_failed
com.comcast.cmb.common.util.PersistenceException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
	at com.comcast.cmb.common.persistence.CassandraAstyanaxPersistence.insertRow(CassandraAstyanaxPersistence.java:646)
	at com.comcast.cqs.controller.CQSControllerServlet.writeHeartBeat(CQSControllerServlet.java:188)
	at com.comcast.cmb.common.controller.CMB.main(CMB.java:81)

I know the message says cassandra is not available but i try making ping to the cassandra server and it work and accesing the port configured in cmb using telnet and it was open.
Is this a compatibility problem? Did anyone has run on this issue before?
I hope you can help me
Have a good day

**Comment by boriwo** [comment]
We have successfully tested CMB with the community version of Cassandra up to version 2.1.7. I know CMB used to work in the past with earlier versions of Datastax Enterprise but we haven't tried recently. The error message you see does sound like a configuration issue rather than a fundamental issue with the Datastax edition. Have you used earlier versions of CMB with Datastax Enterprise?

**Comment by yeiniel** [comment]
No we have not use previous versions of CMB with DSE. In the past we have always used CMB with the Datastax Comunity Edition.

**Comment by cjcurts** [comment]
The CMB contains an example schema for cassandra 12. Is there an updated schema for Cassandra 21 or Cassandra 22? Or can the 1.2 schema work effectively?

Thanks
Chris

**Comment by boriwo** [comment]
We tested the latest version of the schema (1.2) with Cassandra version 2.0.X and I would expect it to work with Cassandra 2.1/2.2 as well.

**Comment by Vermillionaire** [comment]
I've encountered some very similar issues to this. In the newer versions of Cassandra it appears that thrift is disabled by default, so the cmb cannot connect to it. The solution to this is to run _nodetool enablethrift_ while Cassandra is running. This solved my connection issues. Hope this helps anyone running into similar issues!
